version: "3"
services:
    elasticsearch:
        build: ./app/elasticsearch
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data/var/etc/elasticsearch/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
            - /data/var/etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - /data/var/lib/elasticsearch:/usr/share/elasticsearch/data
        networks:
            - elastic
        restart: always
    kibana:
        images: kibana:7.9.3
        container_name: kibana
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        volumes:
            - /data/var/etc/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            ELASTICSEARCH_URL: http://172.17.0.1:9200
        networks:
            - elastic
        restart: always
    logstash:
        images: logstash:7.9.3
        container_name: logstash
        depends_on:
            - elasticsearch
        networks:
            - elastic
        restart: always
    filebeat:
        images: filebeat:7.9.3
        container_name: filebeat
        depends_on:
            - elasticsearch
        volumes:   
            - /data/var/etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /data/var/etc/filebeat/modules.d:/usr/share/filebeat/modules.d
        networks:
            - elastic
        restart: always
networks:
    elastic:
        driver: bridge
