FROM longjianghu/elasticsearch:6.4.0

MAINTAINER Longjianghu <215241062@qq.com>

# 安装IK分词 https://github.com/medcl/elasticsearch-analysis-ik

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.4.0/elasticsearch-analysis-ik-6.4.0.zip