FROM elasticsearch:6.6.2

MAINTAINER Longjianghu <215241062@qq.com>

# 安装IK分词 https://github.com/medcl/elasticsearch-analysis-ik

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.6.2/elasticsearch-analysis-ik-6.6.2.zip
